name: Backend CI

on:
  push:
    paths: ["backend/**"]
  pull_request:
    paths: ["backend/**"]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v8.3.2
        with:
          python-version: 3.13
          enable-cache: true
      - name: install dependencies
        working-directory: backend
        run: uv sync
      - name: Unit tests
        working-directory: backend
        run: uv run pytest tests/units

  integration-test:
    needs: unit-test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: ${{secrets.postgres_password}}
          POSTGRES_DB: RagLabTest
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: 
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v8.3.2
        with:
          python-version: 3.13
          enable-cache: true
      - name: install dependencies
        working-directory: backend
        run: uv sync
      - name: integration tests
        working-directory: backend
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_TEST_DB: RagLabTest
        run: uv run pytest tests/integration
  build-and-push:
    needs: integration-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_version: ${{ steps.meta.outputs.version }}
    steps:
      - name: checkout github actions
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name:  Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/silverd087/raglab-backend
          tags: |
            type=sha,format=short
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  update-manifests:
    needs: build-and-push
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    concurrency:
      group: infra-repo-update
      cancel-in-progress: false
    steps:
      - name: checkout infrastructure repository
        uses: actions/checkout@v4
        with:
          repository: silverd087/RAG-Lab-Infra
          token: ${{ secrets.DEPLOY_REPO_PAT }}
          path: infrastructure-repo
        
      - uses: imranismail/setup-kustomize@v2
      - name: update kustomize image Tag
        working-directory: infrastructure-repo/overlays/dev
        run: kustomize edit set image ghcr.io/silverd087/raglab-backend=ghcr.io/silverd087/raglab-backend:${{ needs.build-and-push.outputs.image_version }}
      
      - name: commit changes
        working-directory: infrastructure-repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff --quiet || git commit -am "raglab-backend ${{ needs.build-and-push.outputs.image_version }}"
          git pull --rebase
          git push

      
